ProtonMail/proton-vpn-settings

src/app/PrivateApp.js, src/app/containers/AccountContainer.js
Related PRs:
~`react-components`: https://github.com/ProtonMail/react-components/pull/175~ ✅
~`proton-shared`: https://github.com/ProtonMail/proton-shared/pull/43~ ✅ 
Fixes: #6
=> Edit OpenVPN account credentials section

src/app/components/sections/plans/PlanPrice.js, src/app/components/sections/plans/PlansTable.js
Fixed some design points on Design system, and updated some points here:
- added color on left column, used correct classname
- updated empty cells
- removed colors on plans (except on "active" one)
- added condition to disable "update" button for current plan
- updated display of plan (removed margin between price and "billed as")
=> Fix - plan table display

package-lock.json, src/app/app.scss, src/app/components/layout/PublicHeader.js, src/app/components/layout/PublicLayout.js, src/app/components/layout/SignInLayout.js, src/app/components/sections/redeem/RedeemCouponForm.js, src/app/containers/RedeemContainer.js, src/app/containers/RedeemContainer.scss
Fix: #92 
Requires:
https://github.com/ProtonMail/react-components/pull/241
✔️ https://github.com/ProtonMail/design-system/pull/213
https://github.com/ProtonMail/proton-shared/pull/47
To test:
Checkout required branches (mentioned above);
`npm link` the projects && `npm start`
=> Redeem page (#81)

src/app/components/layout/PrivateHeader.js
Make logo and other stuff disappear on mobile:
=> Fix rwd - hide main logo on mobile

src/app/components/sections/plans/PlansSection.js
- Added some padding below button (otherwise the button is sticked to table on small reso)
- Added scroll for too large tables
=> Fix - responsive content

src/app/containers/RedeemContainer.js, src/app/containers/RedeemContainer.scss
- Fixed some alignments (title with boxes below)/paddings and use more space on tablet/mobile.
=> Fix responsive on Redeem page

src/app/components/layout/SignInLayout.js
Buttons were not aligned properly, see
- added a flex wrapper and magic
=> Fix button alignment on login

src/app/containers/SignupContainer/PlanStep/PlanStep.js, src/app/containers/SignupContainer/SignupContainer.js
RAISPONSIVE EVERYTHING !!!!
- Made block take the entire space on mobile
=> Fix - responsive signup

src/app/components/header/SupportDropdown.js, src/app/containers/SignupContainer/PlanStep/PlanCard/PlanCard.js, src/app/containers/SignupContainer/PlanStep/PlanStep.js, src/app/containers/SignupContainer/SignupContainer.js
- moved away the "Most popular" badge on tablets
- fixed vertical alignment of support dropdown
=> Fix responsive tablets (plans/etc.)

src/app/containers/SignupContainer/SelectedPlan/PriceInfo.js
=> Adjust price summary to show total for cycle instead of monthly

src/app/containers/SignupContainer/PlanStep/PlanCard/PlanCard.js, src/app/containers/SignupContainer/PlanStep/PlanStep.js, src/app/containers/SignupContainer/PlanStep/PlansGroupButtons.js, src/app/containers/SignupContainer/SignupContainer.js
=> Add PlansGroupButtons in signup for mobile

src/app/containers/SignupContainer/PaymentStep/PaymentStep.js, src/app/containers/SignupContainer/SelectedPlan/PlanUpsell.js, src/app/containers/SignupContainer/SignupContainer.js, src/app/containers/SignupContainer/VerificationStep/VerificationStep.js, src/app/containers/SignupContainer/useSignup.js
During payment or verification, upsell should not be available.
=> Disable upsell in signup while creating account.

src/app/containers/SignupContainer/PlanStep/PlanStep.js, src/app/containers/SignupContainer/PlanStep/PlansGroupButtons.js, src/app/containers/SignupContainer/SignupContainer.js
- reduced padding on mobile
- made button display full widht on mobile (and proper margins)
- fix select plan/etc. mobile behaviour
=> Fix responsive home/etc.

src/app/containers/SignupContainer/SelectedPlan/PlanUpsell.js
=> Fix upsell crashing page when not upselling cycle

src/app/containers/SignupContainer/AccountStep/AccountStep.js, src/app/containers/SignupContainer/PaymentStep/PaymentStep.js, src/app/containers/SignupContainer/SignupContainer.js, src/app/containers/SignupContainer/VerificationStep/VerificationStep.js
- reordered buttons/title
- added border on other steps
=> Fix rwd header buttons

src/app/containers/SignupContainer/SelectedPlan/PlanUpsell.js, src/app/containers/SignupContainer/SignupContainer.js
=> Fix upsell from free to paid not triggering flag

src/app/containers/SignupContainer/PlanStep/PlanCard/PlanPrice.js
- Updated display to make it look like
=> Fix display plan prices

src/app/containers/SignupContainer/AccountStep/AccountForm.js, src/app/containers/SignupContainer/PaymentStep/PaymentStep.js, src/app/containers/SignupContainer/PlanStep/PlanCard/PlanPrice.js, src/app/containers/SignupContainer/PlanStep/PlanStep.js, src/app/containers/SignupContainer/SelectedPlan/PlanUpsell.js, src/app/containers/SignupContainer/VerificationStep/VerificationForm/VerificationCodeForm/ResendCodeModal.js, src/app/containers/SignupContainer/VerificationStep/VerificationForm/VerificationCodeForm/VerificationCodeForm.js, src/app/containers/SignupContainer/VerificationStep/VerificationForm/VerificationForm.js, src/app/containers/SignupContainer/VerificationStep/VerificationForm/VerificationMethodForm/VerificationMethodForm.js
Requires `react-components`: https://github.com/ProtonMail/react-components/pull/265
=> Fix signup console errors and warnings

src/app/containers/SignupContainer/AccountStep/AccountForm.js, src/app/containers/SignupContainer/PaymentStep/PaymentStep.js, src/app/containers/SignupContainer/SignupContainer.js, src/app/containers/SignupContainer/VerificationStep/VerificationForm/VerificationCodeForm/VerificationCodeForm.js, src/app/containers/SignupContainer/VerificationStep/VerificationForm/VerificationMethodForm/VerificationMethodForm.js, src/app/containers/SignupContainer/VerificationStep/VerificationStep.js
- made fields with fluid width
- increase margin between fields and selected plan
- removed border on alert block (design request on account step)
- needs https://github.com/ProtonMail/react-components/pull/266 approved
=> Made fields fluid

src/app/containers/SignupContainer/AccountStep/AccountStep.js, src/app/containers/SignupContainer/LoginPanel.js, src/app/containers/SignupContainer/PaymentStep/PaymentStep.js, src/app/containers/SignupContainer/VerificationStep/VerificationForm/VerificationCodeForm/VerificationCodeForm.js, src/app/containers/SignupContainer/VerificationStep/VerificationForm/VerificationMethodForm/VerificationEmailInput.js, src/app/containers/SignupContainer/VerificationStep/VerificationForm/VerificationMethodForm/VerificationMethodForm.js, src/app/containers/SignupContainer/VerificationStep/VerificationForm/VerificationMethodForm/VerificationPhoneInput.js, src/app/containers/SignupContainer/VerificationStep/VerificationStep.js
Fix https://github.com/ProtonMail/proton-vpn-settings/issues/189
=> Use already have an account? panel

src/app/containers/SignupContainer/VerificationStep/VerificationForm/VerificationCodeForm/ResendCodeModal.js, src/app/containers/SignupContainer/VerificationStep/VerificationForm/VerificationCodeForm/VerificationCodeForm.js
=> Fix invalid property

src/app/containers/SignupContainer/PlanStep/PlanCard/PlanPrice.js, src/app/containers/SignupContainer/SelectedPlan/PlanUpsell.js, src/app/containers/SignupContainer/SignupContainer.js
Related: https://github.com/ProtonMail/react-components/pull/269
=> Loader when creating an account

src/app/containers/SignupContainer/SignupContainer.js
=> Show signup title, but use another loader

src/app/containers/SignupContainer/AccountStep/AccountStep.js, src/app/containers/SignupContainer/PaymentStep/PaymentStep.js, src/app/containers/SignupContainer/PlanStep/PlanStep.js, src/app/containers/SignupContainer/SignupContainer.js, src/app/containers/SignupContainer/VerificationStep/VerificationStep.js
Signup header has a new design.
- Added main logo instead of title
- Moved title below, added new styles to it
- removed top border from steps
- updated paddings
Snaps:
Fixes: #217
=> Feat #217 - new title design/logo

src/app/containers/SignupContainer/SignupContainer.js
=> Use FullLoader to be able to color loader spinner

src/app/containers/SignupContainer/SignupContainer.js
Buttons were not aligned properly.
- added `flex-items-center` to align them correctly
Fixes: #238
=> Fix #238 - buttons alignments

src/app/components/layout/PrivateLayout.js
- added smooth scroll helper `scroll-smooth-touch` on container with scrolling :)
=> Fix #244 - add smooth scrolling on main container

src/app/components/layout/SignInLayout.js
=> Fix #269 ~ Add website link + JS date for the year

src/app/containers/SignupContainer/plans.js
Fixes https://gitlab.protontech.ch/ProtonVPN/web/protonvpn-settings/issues/10
=> Remove duplicated P2P item in pricing table

src/app/containers/SignupContainer/plans.js
Fixes https://gitlab.protontech.ch/ProtonVPN/web/protonvpn-settings/issues/12
=> Add item "All advanced security features" to plans table

src/app/components/layout/PrivateLayout.js
=> Use MainContainer to fix #246

src/app/app.scss
React component import will be simplified, in order to allow creating project specific components and avoid using them if they are not needed.
=> Feat - better CSS import

src/app/components/sections/plans/PlansSection.js
All loyal users will receive a bonus on their paid subscription. We need to display a modal to inform them about this bonus when they try to unsubscribe.
Require https://github.com/ProtonMail/react-components/pull/425 to be merged first.
=> Display loyalty modal when unsubscribe

src/app/containers/SignupContainer/SignupContainer.js
Fixes https://gitlab.protontech.ch/ProtonVPN/web/protonvpn-settings/issues/35
=> Show free plan for Android users.

src/app/containers/SignupContainer/SignupContainer.js
Fixes https://gitlab.protontech.ch/ProtonVPN/web/protonvpncom/issues/386
=> Fixes the issue where we are not showing Free users other plans

src/app/containers/SignupContainer/SignupContainer.js
Fixes https://gitlab.protontech.ch/ProtonVPN/web/protonvpn-settings/issues/35
=> Show free plan if user is coming from mobile

src/app/components/layout/PrivateLayout.js
Fixes https://gitlab.protontech.ch/ProtonVPN/web/protonvpn-settings/issues/57
=> Hide dashboard and payments pages for sub-user

src/app/containers/LoginContainer.js
Fixes https://gitlab.protontech.ch/ProtonVPN/web/protonvpn-settings/issues/57
=> Redirect sub-user to /account page after login
